// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmODdddIgMSk0YU7QSKaYxG29LrZ1vQM',
    appId: '1:274301238146:web:d485576842bf68e420ed9b',
    messagingSenderId: '274301238146',
    projectId: 'vacationproject-33749',
    authDomain: 'vacationproject-33749.firebaseapp.com',
    storageBucket: 'vacationproject-33749.appspot.com',
    measurementId: 'G-JHF3SD9MHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ea-3g-PjMQ8R9V80LsoI-f3O9PsXMX8',
    appId: '1:274301238146:android:1c0621f82327128620ed9b',
    messagingSenderId: '274301238146',
    projectId: 'vacationproject-33749',
    storageBucket: 'vacationproject-33749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqvWMHFzvtmDzqe168L-vSZuDQknucB_I',
    appId: '1:274301238146:ios:1bf51a63caa145dd20ed9b',
    messagingSenderId: '274301238146',
    projectId: 'vacationproject-33749',
    storageBucket: 'vacationproject-33749.appspot.com',
    iosClientId: '274301238146-q7pk035jmk1lhvcjrjqrtd63s436e88q.apps.googleusercontent.com',
    iosBundleId: 'com.example.vacationvproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqvWMHFzvtmDzqe168L-vSZuDQknucB_I',
    appId: '1:274301238146:ios:1bf51a63caa145dd20ed9b',
    messagingSenderId: '274301238146',
    projectId: 'vacationproject-33749',
    storageBucket: 'vacationproject-33749.appspot.com',
    iosClientId: '274301238146-q7pk035jmk1lhvcjrjqrtd63s436e88q.apps.googleusercontent.com',
    iosBundleId: 'com.example.vacationvproject',
  );
}
